name: Test VM Connectivity

on:
  push:
    branches:
      - main  # Trigger the workflow on commits to the main branch

jobs:
  test-vm:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Test connectivity to the VM (Ping Test)
      - name: Test VM Ping
        run: |
          echo "Pinging VM 172.19.14.44..."
          ping -c 4 172.19.14.44 || exit 1

      # Step 3: (Optional) Test SSH Connection to the VM
      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to VM..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa centagateadmin@172.19.14.44 "echo 'SSH connection successful!'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Log Success
      - name: Log Connection Status
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Workflow success: ${TIMESTAMP}" >> connection_log.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add connection_log.txt
          git commit -m "Update connection status log"
          git push
