name: Update VM Status

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Access the VM via SSH
    - name: Connect to VM
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Navigate to the project folder or execute commands
          cd /path/to/project
          ./update-status.sh

    # Step 3: Push Status Changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update status"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
