# Update Docusaurus and Test VM Connectivity
name: Update Docusaurus and Test VM Connectivity

on: push

jobs:
  test-vm:
    runs-on: ubuntu-latest

    steps:
     # Step 1: Install sshpass
      - name: Install sshpass
        run: |
          echo "Installing sshpass..."
          sudo apt-get update && sudo apt-get install -y sshpass

      # Step 2: Test SSH Connection Using Password
      - name: Test SSH Connection Using Password
        run: |
          echo "Testing SSH connection to VM using password..."
          sshpass -p "${{ secrets.VM_PSWD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "echo 'SSH connection successful!'"
