name: Deploy to Server

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          echo "Installing sshpass..."
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          echo "Starting deployment..."
          sshpass -p '${{ secrets.VM_PSWD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} <<'ENDSSH'
          # Navigate to a directory (optional)
          cd /path/to/directory

          # Edit or create the text file with a success message
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Workflow succeeded via SSH at $TIMESTAMP" >> workflow_success.txt

          # Display the updated file contents for confirmation
          cat workflow_success.txt
          ENDSSH

      - name: Confirm Deployment
        run: echo "Deployment workflow completed successfully!"
